In [60]:
import wrds
import pandas as pd
import numpy as np

In [26]:
crsp_db = wrds.Connection(wrds_username='ningtong88')

Loading library list...
Done

In [3]:
#crsp_db.create_pgpass_file()

In [4]:
crsp_db.get_table(library='crsp',table='stocknames',obs=10)

,permno,permco,namedt,nameenddt,cusip,ncusip,ticker,comnam,hexcd,exchcd,siccd,shrcd,shrcls,st_date,end_date,namedum
0,10000.0,7952.0,1986-01-07,1987-06-11,68391610,68391610,OMFGA,OPTIMUM MANUFACTURING INC,3.0,3.0,3990.0,10.0,A,1986-01-31,1987-06-30,2.0
1,10001.0,7953.0,1986-01-09,1993-11-21,36720410,39040610,GFGC,GREAT FALLS GAS CO,2.0,3.0,4920.0,11.0,None,1986-01-31,2017-08-31,2.0
2,10001.0,7953.0,1993-11-22,2008-02-04,36720410,29274A10,EWST,ENERGY WEST INC,2.0,3.0,4920.0,11.0,None,1986-01-31,2017-08-31,2.0
3,10001.0,7953.0,2008-02-05,2009-08-03,36720410,29274A20,EWST,ENERGY WEST INC,2.0,3.0,4920.0,11.0,None,1986-01-31,2017-08-31,2.0
4,10001.0,7953.0,2009-08-04,2009-12-17,36720410,29269V10,EGAS,ENERGY INC,2.0,3.0,4920.0,11.0,None,1986-01-31,2017-08-31,2.0
5,10001.0,7953.0,2009-12-18,2010-07-08,36720410,29269V10,EGAS,ENERGY INC,2.0,2.0,4925.0,11.0,None,1986-01-31,2017-08-31,2.0
6,10001.0,7953.0,2010-07-09,2017-08-03,36720410,36720410,EGAS,GAS NATURAL INC,2.0,2.0,4925.0,11.0,None,1986-01-31,2017-08-31,2.0
7,10002.0,7954.0,1986-01-10,1993-09-29,05978R10,60740110,MBNC,MOBILE NATIONAL CORP,3.0,3.0,6710.0,10.0,None,1986-01-31,2013-02-28,2.0
8,10002.0,7954.0,1993-09-30,2002-05-14,05978R10,83623410,SABC,SOUTH ALABAMA BANCORPORATION IN,3.0,3.0,6710.0,11.0,None,1986-01-31,2013-02-28,2.0
9,10002.0,7954.0,2002-05-15,2013-02-15,05978R10,05978R10,BTFG,BANCTRUST FINANCIAL GROUP INC,3.0,3.0,6020.0,11.0,None,1986-01-31,2013-02-28,2.0

In [5]:
crsp_db.get_table(library='crspm',table='dsf',obs=10)

,cusip,permno,permco,issuno,hexcd,hsiccd,date,bidlo,askhi,prc,vol,ret,bid,ask,shrout,cfacpr,cfacshr,openprc,numtrd,retx
0,23282430,10383.0,8300.0,10910.0,3.0,2830.0,1987-01-19,8.75,9.00,8.75,14950.0,-0.027778,8.75,9.00,11899.0,0.1,0.1,None,39.0,-0.027778
1,23282430,10383.0,8300.0,10910.0,3.0,2830.0,1987-01-20,8.75,9.25,9.00,66203.0,0.028571,9.00,9.25,11899.0,0.1,0.1,None,48.0,0.028571
2,23282430,10383.0,8300.0,10910.0,3.0,2830.0,1987-01-21,9.00,9.50,9.25,36150.0,0.027778,9.25,9.50,11899.0,0.1,0.1,None,44.0,0.027778
3,23282430,10383.0,8300.0,10910.0,3.0,2830.0,1987-01-22,9.00,9.50,9.25,28430.0,0.000000,9.25,9.50,11899.0,0.1,0.1,None,43.0,0.000000
4,23282430,10383.0,8300.0,10910.0,3.0,2830.0,1987-01-23,9.00,9.50,9.25,72900.0,0.000000,9.00,9.25,11899.0,0.1,0.1,None,53.0,0.000000
5,23282430,10383.0,8300.0,10910.0,3.0,2830.0,1987-01-26,8.50,9.25,9.00,22156.0,-0.027027,8.50,9.00,11899.0,0.1,0.1,None,33.0,-0.027027
6,23282430,10383.0,8300.0,10910.0,3.0,2830.0,1987-01-27,8.50,9.25,9.25,29805.0,0.027778,8.75,9.25,11899.0,0.1,0.1,None,32.0,0.027778
7,23282430,10383.0,8300.0,10910.0,3.0,2830.0,1987-01-28,9.00,9.75,9.75,110250.0,0.054054,9.50,9.75,11899.0,0.1,0.1,None,67.0,0.054054
8,23282430,10383.0,8300.0,10910.0,3.0,2830.0,1987-01-29,9.25,9.75,9.25,23950.0,-0.051282,9.00,9.50,11899.0,0.1,0.1,None,37.0,-0.051282
9,23282430,10383.0,8300.0,10910.0,3.0,2830.0,1987-01-30,9.00,9.50,9.50,13204.0,0.027027,9.25,9.50,11899.0,0.1,0.1,None,22.0,0.027027

In [27]:
ticker_list = {'tickers': ('GLD', 'SPY', 'TLT')}

In [28]:
crsp_db.raw_sql('SELECT distinct permco, permno, ticker FROM crsp.stocknames WHERE ticker in %(tickers)s order by 3 asc', params=ticker_list)

    permco   permno ticker
0  23150.0  22568.0    GLD
1  23407.0  26411.0    GLD
2  30433.0  80694.0    GLD
3  45874.0  90448.0    GLD
4   2751.0  33910.0    SPY
5   4215.0  60716.0    SPY
6  46699.0  84398.0    SPY
7  37493.0  89468.0    TLT

In [29]:
crsp_db.raw_sql('SELECT permco, permno, ticker, comnam FROM crsp.stocknames WHERE ticker in %(tickers)s group by permco, permno, ticker, comnam order by 3 asc', params=ticker_list)

    permco   permno ticker                      comnam
0  23150.0  22568.0    GLD                   GOULD INC
1  23407.0  26411.0    GLD       GLADDING MC BEAN & CO
2  30433.0  80694.0    GLD  SANTA FE PACIFIC GOLD CORP
3  45874.0  90448.0    GLD             SPDR GOLD TRUST
4  45874.0  90448.0    GLD     STREETTRACKS GOLD TRUST
5   2751.0  33910.0    SPY  SPEEDRY CHEMICAL PRODS INC
6   4215.0  60716.0    SPY         SPECTRA PHYSICS INC
7  46699.0  84398.0    SPY  SPDR S & P 500 E T F TRUST
8  46699.0  84398.0    SPY                  SPDR TRUST
9  37493.0  89468.0    TLT               ISHARES TRUST

In [30]:
#Permnos for GLD, SPY, and TLT
permno_list_1 = {'permno': ('90448.0','84398.0','89468.0')}

In [32]:
dsf_keep = crsp_db.raw_sql('select b.ticker, a.permno, a.date, a.bidlo, a.askhi, \
    a.prc, a.bid, a.vol, a.ret from crspm.dsf a, crsp.stocknames b \
    where a.permno in %(permno)s and a.permno = b.permno', 
                params=permno_list_1,date_cols=['date'], index_col=['permno'])

In [8]:
#permco_list_df = crsp_db.raw_sql('select distinct permco FROM crsp.stocknames WHERE ticker in %(tickers)s', params=ticker_list)

In [10]:
#permco_list_string = permco_list_df.permco.astype(str).values.tolist()
# permco_list_string = ','.join("'{0}'".format(x) for x in permco_list_string)
#permco_tuple = tuple(permco_list_string)

In [13]:
# permco_result =''
# for i in permco_list_string:
#     if permco_list_string.index(i) == 0:
#         # print (permco_list_string.index(i))
#         temp = '('+'\'' + i + '\'' + ','
#     elif permco_list_string.index(i) == len(permco_list_string) - 1:
#         temp = '\'' + i + '\'' +')'
#     else :
#         temp = '\'' + i + '\'' + ','

#     permco_result += temp
# print (permco_result)

In [35]:
etf_incept_date_range = crsp_db.raw_sql('select permno, min(date), max(date) from crspm.dsf where permno in %(permno)s group by permno order by 2 asc', params=permno_list_1,date_cols=['date'], index_col=['permno'])

In [57]:
#Keep only the data for the assets we want and also only keep the time period that all assets are active
dsf_filtered = dsf_keep[dsf_keep['date'].dt.date >= etf_incept_date_range['min'].max()]

In [ ]:
portfolio_weights = np.array([0.5, 0.4, 0.1])